# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console 로 접속

# Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop